version: '3'

vars:
  TIMEZONE: "'-'"
  GOLANGCI_VERSION: 1.52.2

tasks:
  help:
    cmds:
      - go run . -h

  deps:
    cmds:
      - go mod tidy

  golanci-lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b .bin v{{.GOLANGCI_VERSION}}
      - mv .bin/golangci-lint .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    generates:
      - .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    status:
      - test -f .bin/golangci-lint-{{.GOLANGCI_VERSION}}

  lint:
    deps: [golanci-lint]
    cmds:
        - .bin/golangci-lint-{{.GOLANGCI_VERSION}} run

  lint-reports:
    generates:
      - out/lint.xml

  install:
    deps: [deps]
    cmds:
      - cmd: go install github.com/vendelin8/elements
    generates:
      - $GOPATH/bin/elements

  run:
    deps: [install]
    cmds:
      - elements -loc {{.TIMEZONE}}

  test:
    deps: [deps]
    cmds:
      - echo "testing ..."
      - go test -coverprofile coverage.out ./... -v -timeout 90s

  cover:
    cmds:
      - go tool cover -o cov.html -html=coverage.out; sed -i 's/black/whitesmoke/g' cov.html; chromium cov.html
